apiVersion: v1
kind: PersistentVolume
metadata:
  name: bb-ssl-volume
  namespace: production
spec:
  storageClassName: yc-network-hdd
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/beautybox/ssl"