apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bb-ssl-volume-claim
  namespace: production
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
