apiVersion: v1
kind: PersistentVolume
metadata:
  name: kitman-pv
spec:
  storageClassName: yc-network-hdd
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce 
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: ef3h5789rdr9ie8jp820
