apiVersion: v1
kind: PersistentVolume
metadata:
  name: bb-mysql-volume
  namespace: production
spec:
  storageClassName: yc-network-ssd
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: fhmlovlcr16hgk1e8288
    volumeAttributes:
      volumePath: "/var/www/csi-testt"
#  hostPath:
#    path: "/mnt/data"