apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bb-php-volume-claim
  namespace: production
spec:
  storageClassName: s3-beautybox
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
